export { angleDiff } from "./angle";
export {
  createLightweightCatchLog,
  isLightweightCatchLog,
  isLightweightCatchLogArray,
  type CreateLightweightCatchLogInput,
  type LightweightCatchLog
} from "./catchLog";
export {
  ENVIRONMENTAL_REQUIRED_FIELDS,
  ENVIRONMENTAL_SCHEMA_VERSION,
  ENVIRONMENT_WINDOW_HOURS,
  buildEnvironmentalFeatureVector,
  calculateDataFreshness,
  calculateEnvironmentalQuality,
  calculateMissingFields,
  calculateMissingRate,
  detectEnvironmentalContradictions,
  detectRapidEnvironmentalChanges,
  environmentalSnapshotKey,
  type DataProvenance,
  type EnvironmentWindowHour,
  type EnvironmentWindowKey,
  type EnvironmentalContradiction,
  type EnvironmentalFeatureVector,
  type EnvironmentalQualityReport,
  type EnvironmentalSnapshot,
  type MarineObservation,
  type RapidChange,
  type WeatherObservation,
  type WindContinuity
} from "./environment";
export {
  calculateGraphSummary,
  findShortestPathByDistance,
  getAdjacentNodes,
  getConnectedComponents,
  getHabitatNode,
  getIncomingEdges,
  getOutgoingEdges,
  haversineDistanceKm,
  roundDistanceKm,
  validateHabitatGraph,
  type BayPosition,
  type ConnectionType,
  type DepthBand,
  type Directionality,
  type HabitatEdge,
  type HabitatGraph,
  type HabitatGraphSummary,
  type HabitatNode,
  type HabitatType,
  type HabitatValidationResult,
  type ShortestHabitatPath,
  type WaterBodyType
} from "./habitat";
export {
  HABITAT_GRAPH_VERSION,
  INITIAL_HABITAT_EDGE_SEEDS,
  createHabitatNodeFromEnvironmentNode,
  createInitialHabitatGraph,
  type EnvironmentNodeSeed
} from "./habitat-fixtures";
export {
  DEFAULT_SPECIES_FRESHNESS,
  calculateFreshness,
  findConflictingEvidence,
  findDuplicateCandidates,
  scoreEvidenceReliability,
  validateEvidenceEvent,
  type BacktestResult,
  type ConflictCandidate,
  type DuplicateCandidate,
  type EvidenceEvent,
  type EvidenceSource,
  type EvidenceSourceKind,
  type EvidenceValidationResult,
  type FishPresenceEstimate,
  type FreshnessResult,
  type HabitatFeature,
  type LocationEstimate,
  type MovementEstimate,
  type PredictionSnapshot,
  type ReliabilityBreakdown,
  type SpeciesFreshnessProfile,
  type SpeciesObservation
} from "./intelligence";
